language: python
os:
- linux
python:
    - "3.6"
    - "3.7"
    - "3.8"
install: pip install -U pip
script:
#- pip install git+https://github.com/zfit/zfit
- pip install -U .
- pip install -r requirements_dev.txt
#- bash utils/ci/test_examples.sh
- ls
- ls /home/travis/build
- ls /home/travis/build/zfit
- coverage run --source=/home/travis/build/zfit --branch -m pytest --basetemp={envtmpdir}
- coverage report
after_success:
- pip install coveralls
- coveralls
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  user: zfit
  password:
    secure: cF//6Ssabb/w427Ff3NBRj7sCujkKGF8i+UTfW+XTkvijPT8rpKe367h9gJ8swMV9DqmuCc8cftfp9VknrrVJwFcjWbWpHV4MekvBhTc5foMxGsjT34PA7ircTAr0UAC0Og+T+z0g/V8bVfyt7U2wzs2raO9E21twtqeaXZ/K0nTDEr83fjOiBhAQmh79XCr20HCBnzTvZU9GV9vVbYGNS+Uq2Riyh4/ry7Rh7WgvMegk9e3/GEZ2TMQXWdGIW8Fu+8XwVCSSstbHNxFci8GtzWMl2zBbaxcAJikzVmpP56hgIbwJzxxCeoVnRucAIkpIqaI5AMbL1hxu9uYeaEGVi9qrpHOpEwC46cmVMIVmk3mm9UY1tOTEXf2IwAYg8bJXFovj7kU1fJfLfa7PbCViQ29OXfZKpSoyBYiIGZ2XRG22OcsUK5K8KIq23+OtCGLt2jbloNXR5QOnSenw/LByNoutvuV545wrbjRyWCVygcONRfO7g9c0pSOk6mxqjqhK9nUKBVsEz88BNVnriExsjOyp4ch/42TLmheDE0BVcPTRiqSysrkDzmwBBe/HkTJZRczbwYIs4G9skTiuazWu4tbNQaRrxavFqL6kZUQFTmN7pb7Ig2M91sLnVe5uxHCVXveKOMHNctmU4us1zBiWGbHsfmt9l6z0WzVxnlhnWs=
    branch: master
    tags: true
    repo: zfit/zfit-physics
    python: 3.8
- provider: pages
  skip_cleanup: true
  github_token:
    secure: loN6oKtEEicR8O71eoeZLO7KEKjtE1EIo1FpWykbUmCB8KEFJz0KtDwwEcT9at2i3LfG6MEccaHtfTwsXycnP3YktFnFA+C0MxTgeKF1evWC1S/xED/vRr3OjczVjrhjZ4viDJmPGr4O+VaMeNf9usde9OmRBdUWUV7qhKk2CZwh8GcBH4XkbtdjQrQoXSJa4WVl6Ix0NNdQ/ckfQIt2Gw7HF2bggRdT31rGWx2FEHJUsb5632LJRCbkC/5p3N24Eqih0G472Q9DwrnZ3AqqjK+mLmFAghw6fy1992FqqH6QCZ9gbDkXmQqIQ0aL37A1S15NtDRXmj/a8uL5E76F4ybP3aKvxsPhkcTLK+ATk2rYtlAc+wD6/L+rUdKJEDZx855+aMhcS5F6mXBXjlTPLf1NU7jWcUjdIzEuLDOATmQs9EcFX3sv7sS8XB+Zrp4P2QpBHWuUlzmHqC6lVFLNSieqioHxXgvvIUyxHW5rVnkP2/FGUw0tyWtLO+8B/20d+Wdrgza2e5qmKK1s1YvmY7IkDc6IgbG8oMVnx7bsZmH7R3ZbT34T2qM7gPi5zM/C0Z+1HS5b2rG36HMlRVWEPFj+AhbnmHXCHlyUttbhcPzvYnuPspvaz4nyFXfv0JP+LMfJ+JhqExk1cKOLl6Ec4zN9z5icXAgpDeKZOViiUk8=
  local_dir: docs/_build/html
  keep-history: true
  on:
    branch: develop
    condition: $TRAVIS_PYTHON_VERSION = "3.8" && $TRAVIS_OS_NAME = "linux"
